version: 0.2
env:
  parameter-store:
    NEXT_PUBLIC_DISCORD_CLIENT_ID: "/heroic-site/NEXT_PUBLIC_DISCORD_CLIENT_ID"
    DISCORD_CLIENT_SECRET: "/heroic-site/DISCORD_CLIENT_SECRET"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building Next.js site...
      - npm run build
      - echo Checking output directory...
      - pwd
      - ls -la
      - ls -la out/
artifacts:
  files:
    - '**/*'
  base-directory: out
